ceph/ceph-iscsi-cli

- gwcli/hostgroup.py
Added help_intro to the hostgroup classes, which is shown by the
shell's help command
> hostgroup: add help text to classes

- gwcli/client.py
- gwcli/utils.py
rtslib silently strips some special characters, so this update restricts
the chars in the password to characters known to work, and updates the
help text to reflect the chars that can be used in a password
> client/auth: fix special characters accepted in UI

- gwcli/client.py
- gwcli/hostgroup.py
- gwcli/node.py
- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
addresses the sequence issue when defining a group (disk first then host or vice-versa)
NB. Requires the changes provided by the ceph-iscsi-config group-fix branch
> Patches to tidy up host group management

- gwcli/storage.py
- rbd-target-api.py
Address the disk delete issues when the image_id supplied is invalid. The cli now ensures the disk is actually valid prior to issuing the api call, and the api itself validates that the image_id format matches a pool.image pattern
> Fix ui delete

- gwcli/hostgroup.py
Logic didn't account for the mode of add/remove when validating the
request. This fix addresses that.
> hostgroup: fix for disk removal from a hostgroup

- gwcli/client.py
- gwcli/utils.py
Updates the valid_credentials function to restrict username syntax, and also improves the help text to provide better guidance on format. 
nb. the strings received by gwcli are pre-parsed by configshell, so some special chars are removed before this codebase sees them (e.g. '!' symbols...cause truncation)
> client auth logic updated to improve username/password validation

- rbd-target-api.py
rtslib_fb will return a "LUN must be 0 to 255" error when
initializing a LUN object.
> Prevent creation of more than 256 disks

- gwcli/gateway.py
Addresses BZ1498764 where an export request is made, before the configuration
is created.
> gateway - catch export requests made when the config is empty

- gwcli/gateway.py
“ValueError: list.remove(x): x not in the list" is not clearly to address problem.
> gateway: Throw the error message more clearly

- rbd-target-api.py
If create gateway is close behand creating target and without refreshing config, this action will be failed because of target_iqn is None.
> rbd-target-api: fix create gateway issue

- gwcli.py
- gwcli/gateway.py
- gwcli/storage.py
Use multi-threaded approach when fetching the size and features of the rbds defined to the config to cut down on start up time. This update sets an 8 thread default. We could in future, set the parallelism based on the number of disks in the config to scan to try and keep start up times around 1sec..just a thought
> Reduce startup time

- gwcli.8
PR:
https://github.com/ceph/ceph-iscsi-config/pull/45
adds support for IQN based ACLs. This patch adds gwcli
documentation.
> doc: Add info about IQN ACL based verification.

- rbd-target-api.py
"gateways.remove(local_host)" should before "logger.debue('other gateways.....')"
> Position correction of function gateways.remove(local_host)

- gwcli/storage.py
- rbd-target-api.py
This parameter specifies the size of data part of the ring buffer.
For LUNs with higher throughput, it would be beneficial to have a
larger ring buffer. This commit makes use of optional "control arg"
commit in ceph-iscsi-config to pass in control arguments when
creating a LUN.
Signed-off-by: Venky Shankar <vshankar@redhat.com>
> gwcli: accept optional "ring_buffer_size" when creating LUNs

- gwcli/storage.py
- gwcli/utils.py
- rbd-target-api.py
This command allows the user to modify and/or reset to default
various LUN attributes. To start with, this allows to modify
(or reset) the ring buffer size (max_data_area_mb).
Command format:
- modify max_data_area_mb
reconfigure image_id=rbd.disk_1 max_data_area_mb=128
- reset max_data_area_mb
reconfigure image_id=rbd.disk_1 max_data_area_mb=
Signed-off-by: Venky Shankar <vshankar@redhat.com>
> gwcli: add reconfigure command to tune various lun attributes

- rbd-target-api.py
The gw manage(map) call calls map_luns which could already fail due
to a LUN() creation error. It can now also fail due to invalid failover
type be set with this patch
https://github.com/ceph/ceph-iscsi-config/pull/69
commit 6738e54aab2db2345f3660c6403b2b1dbee81646
Author: Mike Christie <mchristi@redhat.com>
Date:   Mon Jul 23 16:45:30 2018 -0500
Detect and handle invalid alua failover types
This patch has rbd-target-api check for gateway.error being set by a
caller which was not checking for errors. As far as I can tell the other
map callers are already checking for errors.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> Check for gw manage map errors

- rbd-target-api.py
If the lun is not mapped to an ACL then it is not exported to an
initiator. We can then deactivate it without worrying about the initiator
getting LUN does not exist errors and tearing down the LUN.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> Only check mapped luns during deactivation

- gwcli/storage.py
I got an erorr when creating a disk:
```
/disks> create rbd disk_q 10g 1 8
ok
GatewayAPIError: Unable to retrieve disk details for 'rbd.disk_q1' from the API
```
Surprisingly `count > 1` is true, so I printed `type(count)` and got `<type 'str'>`
```
self.logger.debug("=== type(count): {}".format(type(count)))
if count > 1:
disk_key = "{}.{}{}".format(pool, image, n)
else:
disk_key = "{}.{}".format(pool, image)
```
use `int(count) ` to fix it.
> gwcli/storage: count is not a number when creating disks

- rbd-target-api.py
> rbd-target-api: disable the built-in werkzeug debugger

- ceph-iscsi-cli.spec
The openSUSE Factory review process imposes a requirement that the group
has to be one listed on this page:
https://en.opensuse.org/openSUSE:Package_group_guidelines
Instead of trying to convince the openSUSE Factory reviewers to create
a new group, just use the same group as Ceph itself.
Signed-off-by: Nathan Cutler <ncutler@suse.com>
> build/ops: rpm: set a group that will be recognized by openSUSE

- ceph-iscsi-cli.spec
see https://rpm-guide.readthedocs.io/en/latest/rpm-guide.html#rpm-macros
Signed-off-by: Nathan Cutler <ncutler@suse.com>
> build/ops: rpm: use %license macro unconditionally

- README
- gwcli.8
The default port is 5000 so update the docs.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> Fix default api port references

- ceph-iscsi-cli.spec
- rbd-target-api.py
- setup.py
The ceph selinux policy expects the logs to be in a dir under /var/log,
so this just moves our logs to /var/log/rbd-target-gw, so we do not have
to special case the ceph iscsi stuff in ceph-selinux.
> Move logs to dir

- rbd-target-api.py
Drop out check and rely on the valid_disk check added in PR:
https://github.com/ceph/ceph-iscsi-config/pull/98
This fixes a bug where we try to add disk 256 and on the initial node
it works. But because the initial node does a lun.allocate that adds
the disk to the config, and the other nodes will hit the max lun check
which checks the config and fail to add the disk. It then leaves the
rbd image in the config.
> Use ceph-iscsi-config lun check

- rbd-target-api.py
The error message from rtslib was being dropped when a control could not
be updated. This passes it back to gwcli and also syncs up the tpg error
msg with the client one.
> Fix client reconfigure error message

- gwcli/node.py
The generic info help is a little user unfriendly because the return
None part looks like a bug. This patch drops that part and the generic
handler part of what gets displayed.
> Make generic info help a little nicer
