ceph-iscsi-cli.spec
=> spec: fixed typo for %{_sysconfdir}

ceph-iscsi-cli.spec, gwcli/gateway.py, gwcli/hostgroup.py, rbd-target-api.py
Host group management tidied up (messages formats etc), and additional api added to allow gateways to be checked prior to any change. Now if any gateway is down, changes are simply aborted - instead of the potential of gateways getting out of sync
=> fixes to CLI relating to host group management tasks

usr/lib/systemd/system/rbd-target-api.service
=> Improved systemd limits and system protection

gwcli/ceph.py, gwcli/gateway.py, gwcli/utils.py, rbd-target-api.py
Multiple updates including;  gateway creation changes, gateway validity (s/w version checks) and ceph module updates to provide more health information for the ceph cluster (via an 'info' command)
=> Fix health

gwcli/storage.py
Additional validation prevents a malformed request from triggering an
exception
=> storage: add further validation to disk create request

gwcli/ceph.py
=> Corrected health check summary scrap logic for Luminous

rbd-target-api.py
Previously the seed gateway list was initialized to None.
=> Properly construct seed gateway list

rbd-target-api.py
=> rbd-target-api: remove useless internal_text

gwcli/client.py
Prior to this change if the admin wanted to know the IP address corresponding
to a client iqn, they'd have to open targetcli. With this change the
ip address(es) and alias is shown on an info command (updated whenever
the client is queried)
=> client: updated to include ip addr and alias for an info command

rbd-target-api.py
1, Fix the old docs which have been forgotten to be updated
2, Add detail examples for all APIs, this will be help new users could to use this without reading too much about the codes.
3, get_disks API adds 'detail=yes' parameter support
This will save much system time and resources when there are hundreds of disks here.
=> rbd-target-api.py: fix and add new params support for get_disks

rbd-target-api.py
=> rbd-target-api: adjust minimum supported kernel version

README
Instructions for rpm based and manual installs.
=> rpm and manual install instructions

ceph-iscsi-cli.spec, gwcli.py, setup.py
=> bump version to 2.6

rbd-target-api.py
=> Prevent ValueError for kernels with multiple dashes

rbd-target-api.py
=> Relax OS distro check to support CentOS and RHEL >=7.4

ceph-iscsi-cli.spec, gwcli.py, setup.py
=> ceph-iscsi-cli v2.7

ceph-iscsi-cli.spec
we need python-rtslib >= 2.1.fb64
Change-Id: I748302e2da6ad49d78e07ebc1111cb9caee9ba23
=> modify the version dependency on python-rtslib

rbd-target-api.py
Node addition does not sync existing luns/clients because
it interprets nosync as a bool but request.form.get is
returning a string. The seed_disks/luns functions are then
never called (seed_disk seems to have not been finished as
there is no node=sync for the disk put command).
This has the _gateway put command just call define_clients/disks
added in the ceph-iscsi-config PR to setup the luns and disks
if requested.
This requires:
https://github.com/ceph/ceph-iscsi-config/pull/57
=> Fix node addition

gwcli/storage.py, gwcli/utils.py, rbd-target-api.py
This displays kernel control attributes either overridden
or the default (if any).
Signed-off-by: Venky Shankar <vshankar@redhat.com>
=> gwcli: add "controls" attribute to disk info command

gwcli/gateway.py
=> gwcli/gateway: handle unauthorized response codes from API

rbd-target-api.py
Also replace 'if x[y] else None' with x.get(y)'
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>
=> Replace 'has_key()' with 'in' for Python 3 compatibility

rbd-target-api.py
Signed-off-by: Zheng Yin <zhengyin@cmss.chinamobile.com>
=> ceph-iscsi-cli: remove debug log lines

gwcli/ceph.py, gwcli/client.py, gwcli/storage.py, gwcli/utils.py, rbd-target-api.py
Just some misc patches.
The only interesting patch may be:
"Use ceph-iscsi-config valid_disk"
This patch requires the ceph-iscsi-config addition:
https://github.com/ceph/ceph-iscsi-config/pull/76
=> Misc fixes

ceph-iscsi-cli.spec
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
=> ceph-iscsi-cli.spec: updated URLs, bumped up version

gwcli/gateway.py
=> gateway: fixed issues with ansible export

gwcli/storage.py, rbd-target-api.py
Also allow underscores to be used in rbd pool and image names (I personally prefer them over dashes :wink:).
Note: requires https://github.com/ceph/ceph-iscsi-config/pull/79
=> Improve unexpected error handling within API

COPYING, ceph-iscsi-cli.spec
Signed-off-by: Nathan Cutler <ncutler@suse.com>
=> build/ops: rpm: add copyright notice and COPYING file

gwcli/ceph.py, gwcli/hostgroup.py, gwcli/utils.py, rbd-target-api.py
=> Fixed flake8 warnings

gwcli.8, gwcli/ceph.py, gwcli/client.py, gwcli/gateway.py, gwcli/hostgroup.py, gwcli/storage.py, gwcli/utils.py, rbd-target-api.py
=> Initial support for IPv6

gwcli/storage.py
=> gwcli: validate size on resize UI action

gwcli/client.py, gwcli/gateway.py, gwcli/hostgroup.py, gwcli/node.py
Just some fix ups for the info/help commands.
=> Misc info and help fixes

gwcli/gateway.py
Add kernel's limits to the help command for target controls.
=> Doc target control limits
